spring.application.name=namingServer

server.port=8761

# Enable Eureka Server
eureka.server.enableSelfPreservation=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


#redis
spring.redis.host=127.0.0.1
spring.redis.port=6379
